version: "3.9"

services:
  api:
    build: .
    image: social-discovery-service:latest
    command: ["uvicorn", "social_discovery_service.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/social_discovery
      REDIS_URL: redis://redis:6379/0
      ADMIN_API_KEYS: admin-key
      SUBMITTER_API_KEYS: submit-key
      ENABLE_METRICS: "true"
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/workspace

  worker:
    build: .
    image: social-discovery-service:latest
    command: ["python", "-m", "social_discovery_service.cli", "worker"]
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@postgres:5432/social_discovery
      REDIS_URL: redis://redis:6379/0
      ADMIN_API_KEYS: admin-key
      SUBMITTER_API_KEYS: submit-key
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social_discovery
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  pgdata:
